language: ruby
services:
  - postgresql
before_install:
  - gem install bundler -v '~> 1.5'
before_script:
  - psql -c "create database uniara_virtual_api_test;" -U postgres
rvm:
  - 2.2.1
bundler_args: --without debug
